logging:
  level:
    root: INFO
    # Shows renews
    com.netflix.eureka.resources.InstanceResource: DEBUG
    # Shows Eureka instance registry calls between Eureka server instances
    com.netflix.eureka.registry.AbstractInstanceRegistry: DEBUG
    com.netflix.discovery: DEBUG
spring:
  application:
    name: eureka-client   
server:
  port: 8080      
eureka:
  client:   
    serviceUrl:
      defaultZone: http://3.95.216.138:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,configprops